### ISSUE TITLE
Fatal error in wp-elements.php

### ISSUE THREAD

**Issue by ByteToByte** [picocodes/aLs#1]
Fatal error: Using $this when not in object context in wp-elements.php on line 325
If I activate plugin frontend not works, cause get f/error and if open plugin page settings

need php 5.4 ?

**Comment by ByteToByte** [comment]
I change to php 5.4 and page settings now working, but I had a new bug in frontend Fatal error: Call to undefined function sanitize_hex_color() in /wp-content/plugins/ajax-live-search/includes/hooks.php on line 14

**Comment by ByteToByte** [comment]
I added in hooks.php

```
if ( ! function_exists( 'sanitize_hex_color' ) ) {
	function sanitize_hex_color( $color ) {
		if ( '' === $color ) {
			return '';
		}
		// 3 or 6 hex digits, or the empty string.
		if ( preg_match('|^#([A-Fa-f0-9]{3}){1,2}$|', $color ) ) {
			return $color;
		}
	}
}
```

**Comment by picocodes** [comment]
Hi. The minimum requirements are PHP 5.4 and WordPress 4.6 . Good to see that your hack worked!?

**Comment by ByteToByte** [comment]
Worked
